<?php

declare(strict_types=1);

use Algolia\AlgoliaSearch\Block\Widget\LookingSimilar;
use Blackbird\HyvaAlgoliaSearch\ViewModel\InstantSearchViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var LookingSimilar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$isEnabled = $block->isLookingSimilarEnabled();
$uniqueToken = $block->generateUniqueToken();

/** @var InstantSearchViewModel $viewModel */
$viewModel = $viewModels->require(InstantSearchViewModel::class);

if ($isEnabled):
    $lsContainer =  'lsItems' . $block->generateUniqueToken(); ?>
    <div id="<?= $escaper->escapeHtmlAttr($lsContainer) ?>" class="LSItem recommend-component"></div>
    <script>
        function initRecommendLS<?= $uniqueToken ?>() {
            Promise.all([
                <?php foreach($viewModel->getRecommendedLSScripts() as $script) :?>
                blackbird.loadExternalResource("<?= $script ?>"),
                <?php endforeach; ?>]
            ).then(data => {
                window.addEventListener('init-algolia-LS-done', function () {
                    initAlgoliaRecommendedLS("<?= $escaper->escapeJs($lsContainer) ?>", "<?= $block->getData('numOfLookingSimilarItem') ?>", "<?= $block->getProductIds() ?>");
                });

                window.dispatchEvent(new CustomEvent('init-algolia-LS'));
            });
        }
        window.addEventListener('DOMContentLoaded', function (){
            initRecommendLS<?= $escaper->escapeJs($uniqueToken) ?>();
        });

    </script>
<?php endif; ?>
