<?php

declare(strict_types=1);

use Algolia\AlgoliaSearch\Block\Widget\TrendsItem;
use Blackbird\HyvaAlgoliaSearch\ViewModel\InstantSearchViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var TrendsItem $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$isEnabled = $block->isTrendingItemEnabled();
$uniqueToken = $block->generateUniqueToken();

/** @var InstantSearchViewModel $viewModel */
$viewModel = $viewModels->require(InstantSearchViewModel::class);

if ($isEnabled):
    $trendConstainer = 'trendItems' . $uniqueToken; ?>
    <div id="<?= $escaper->escapehtmlAttr($trendConstainer) ?>" class="trendsItem recommend-component"></div>
    <script>
        function initRecommendTrends<?= $uniqueToken ?>() {
            Promise.all([
                <?php foreach($viewModel->getRecommendedTrendsScripts() as $script) :?>
                blackbird.loadExternalResource("<?= $script ?>"),
                <?php endforeach; ?>]
            ).then(data => {
                window.addEventListener('init-algolia-trends-done', function () {
                    initAlgoliaRecommendedTrends("<?= $escaper->escapeJs($trendConstainer) ?>", "<?= $block->getData('numOfTrendsItem') ?>", "<?= $block->getData('facetName') ?>", "<?= $block->getData('facetValue') ?>");
                });

                window.dispatchEvent(new CustomEvent('init-algolia-trends'));
            });
        }
        window.addEventListener('DOMContentLoaded', function (){
            initRecommendTrends<?= $escaper->escapeJs($uniqueToken) ?>();
        });

    </script>
<?php endif; ?>
